logging:
  level:
    blog: WARN
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor: TRACE
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/reg_form_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 800MB
      max-request-size: 815MB
         

    
    
    
    
    